inline:
  - '-on'
  - '-off'
  - '-recursive'
style:
  - stp
factor:
  - 0
  - 2
state:
  - '-on'
  - '-off'
arrtype:
  - block
  - cyclic
opimpl:
  int:
    - dsp
    - fabric
  float:
    - fabric
    - fulldsp
    - primitivedsp
  double:
    - fabric
    - fulldsp
  half:
    - fabric
    - fulldsp
sttype:
  - fifo
  - ram_1p
  - ram_1wnr
  - ram_2p
  - ram_s2p
stimpl:
  - bram
latency:
  - -1
POW:
  - 0.278
CLK:
  - 6.187
LATENCY:
  - 1000
LUT:
  - 652
FF:
  - 454
DSP:
  - 6
BRAM:
  - 0
URAM:
  - 0
SRL:
  - 0
